# Generated by Django 4.2 on 2023-04-07 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ORM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('descriprition', models.CharField(max_length=1000)),
                ('boock_pic', models.ImageField(upload_to='profile_pictures/')),
                ('boock', models.FileField(upload_to='')),
                ('reting', models.IntegerField()),
                ('saved', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Women',
        ),
    ]
